### ISSUE TITLE
Catkin_make error

### ISSUE THREAD

**Issue by RatheeshRK** [joffman/ros_object_recognition#1]
Error while performing catkin_make

__________________________________________________________
-------
----
CMake Error at object_detection_3d/CMakeLists.txt:45 (include):
  include called with wrong number of arguments.  include() only takes one
  file.

-- +++ processing catkin package: 'distance_filter'
-- ==> add_subdirectory(distance_filter)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'shape_detector'
-- ==> add_subdirectory(shape_detector)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'object_detection_3d_nodes'
-- ==> add_subdirectory(object_detection_3d_nodes)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- +++ processing catkin package: 'whs_navigation'
-- ==> add_subdirectory(whs_navigation)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Configuring incomplete, errors occurred!
See also "/home/rrk/ros_object_recognition/build/CMakeFiles/CMakeOutput.log".
See also "/home/rrk/ros_object_recognition/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by Abdurrasith** [comment]
Im also getting error for CMake too...

**Comment by Andrew-NN** [comment]
Did you run next command in root of your catkin workspace directory before start catkin_make:
`source devel/setup.bash`
?

**Comment by joffman** [comment]
I've updated the CMakeLists.txt files and added a compilation-section in the README.
Please reopen the issue if you still get compilation errors.

PS: Now I get some warnings when I compile the project, but no errors.
       Feel free to clean up the CMakeLists.txt files...
